"""empty message

Revision ID: 1d173a3d8a52
Revises: 
Create Date: 2020-08-13 13:33:24.631029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d173a3d8a52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ih_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ih_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ih_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('image_url', sa.String(length=240), nullable=True),
    sa.Column('real_name', sa.String(length=30), nullable=True),
    sa.Column('real_id_card', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('real_id_card'),
    sa.UniqueConstraint('real_name')
    )
    op.create_table('ih_houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('acreage', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('beds', sa.String(length=64), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('min_days', sa.Integer(), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('default_image_url', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['ih_areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ih_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ih_house_facilities',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['ih_facilities.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['ih_houses.id'], )
    )
    op.create_table('ih_house_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['ih_houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ih_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('order_num', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PAID', 'ACCEPTED', 'COMPLETED', 'REJECTED', 'CANCELLED'), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['ih_houses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ih_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ih_orders_order_num'), 'ih_orders', ['order_num'], unique=True)
    op.create_index(op.f('ix_ih_orders_status'), 'ih_orders', ['status'], unique=False)
    op.drop_table('old_ih_house_image')
    op.drop_table('old_ih_facility_info')
    op.drop_index('ix_ih_order_info_status', table_name='old_ih_order_info')
    op.drop_table('old_ih_order_info')
    op.drop_table('old_ih_area_info')
    op.drop_table('old_ih_house_info')
    op.drop_table('old_ih_house_facility')
    op.drop_index('mobile', table_name='old_ih_user_profile')
    op.drop_index('name', table_name='old_ih_user_profile')
    op.drop_table('old_ih_user_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_ih_user_profile',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('real_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id_card', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('avatar_url', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'old_ih_user_profile', ['name'], unique=True)
    op.create_index('mobile', 'old_ih_user_profile', ['mobile'], unique=True)
    op.create_table('old_ih_house_facility',
    sa.Column('house_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('facility_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['old_ih_facility_info.id'], name='old_ih_house_facility_ibfk_1'),
    sa.ForeignKeyConstraint(['house_id'], ['old_ih_house_info.id'], name='old_ih_house_facility_ibfk_2'),
    sa.PrimaryKeyConstraint('house_id', 'facility_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('old_ih_house_info',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('area_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('room_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('acreage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('beds', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('deposit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('index_image_url', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['old_ih_area_info.id'], name='old_ih_house_info_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['old_ih_user_profile.id'], name='old_ih_house_info_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('old_ih_area_info',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('old_ih_order_info',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('house_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('begin_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('house_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('WAIT_ACCEPT', 'WAIT_PAYMENT', 'PAID', 'WAIT_COMMENT', 'COMPLETE', 'CANCELED', 'REJECTED'), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['old_ih_house_info.id'], name='old_ih_order_info_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['old_ih_user_profile.id'], name='old_ih_order_info_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ih_order_info_status', 'old_ih_order_info', ['status'], unique=False)
    op.create_table('old_ih_facility_info',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('old_ih_house_image',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('house_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['old_ih_house_info.id'], name='old_ih_house_image_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
