"""empty message

Revision ID: 5b1a111b0be0
Revises: 21d5f9cad4ac
Create Date: 2020-09-02 07:57:34.905431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1a111b0be0'
down_revision = '21d5f9cad4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_orders', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_orders', 'trade_no')
    # ### end Alembic commands ###
