"""empty message

Revision ID: 75639e57b527
Revises: 977239a5fbd9
Create Date: 2020-08-24 15:22:55.085902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75639e57b527'
down_revision = '977239a5fbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ih_houses_user_id_title', 'ih_houses', ['user_id', 'title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ih_houses_user_id_title', 'ih_houses', type_='unique')
    # ### end Alembic commands ###
