"""empty message

Revision ID: 8d2ee79de635
Revises: 5b1a111b0be0
Create Date: 2020-09-02 09:52:25.398784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d2ee79de635'
down_revision = '5b1a111b0be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ih_orders_status', table_name='ih_orders')
    op.drop_column('ih_orders', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_orders', sa.Column('status', mysql.ENUM('NEW', 'PAID', 'ACCEPTED', 'COMPLETED', 'REJECTED', 'CANCELLED'), nullable=True))
    op.create_index('ix_ih_orders_status', 'ih_orders', ['status'], unique=False)
    # ### end Alembic commands ###
